#!/bin/bash

# Documentation Link Monitor
# Monitors documentation for broken links and generates reports

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DOCS_DIR="$REPO_ROOT/docs"
FRONTEND_DIR="$REPO_ROOT/frontend"
REPORTS_DIR="$REPO_ROOT/reports/documentation"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Create reports directory if it doesn't exist
mkdir -p "$REPORTS_DIR"

echo -e "${BLUE}🔍 Starting Documentation Link Monitor...${NC}"
echo "Repository: $REPO_ROOT"
echo "Documentation: $DOCS_DIR"
echo "Reports: $REPORTS_DIR"
echo ""

# Function to check links in a file
check_file_links() {
    local file="$1"
    local relative_path="${file#$REPO_ROOT/}"
    
    echo -e "${BLUE}Checking: $relative_path${NC}"
    
    # Run markdown-link-check and capture output
    if npx markdown-link-check "$file" > "${REPORTS_DIR}/$(basename "$file").log" 2>&1; then
        echo -e "${GREEN}✅ All links working in $relative_path${NC}"
        return 0
    else
        echo -e "${RED}❌ Found broken links in $relative_path${NC}"
        return 1
    fi
}

# Function to generate link health report
generate_link_report() {
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    local report_file="$REPORTS_DIR/link-health-report-$(date '+%Y%m%d-%H%M%S').md"
    
    echo "# Documentation Link Health Report" > "$report_file"
    echo "" >> "$report_file"
    echo "**Generated**: $timestamp" >> "$report_file"
    echo "**Repository**: $(git remote get-url origin 2>/dev/null || echo 'Local repository')" >> "$report_file"
    echo "**Branch**: $(git branch --show-current 2>/dev/null || echo 'Unknown')" >> "$report_file"
    echo "" >> "$report_file"
    
    echo "## Summary" >> "$report_file"
    echo "" >> "$report_file"
    
    local total_files=0
    local files_with_broken_links=0
    local total_links=0
    local broken_links=0
    
    # Process all log files
    for log_file in "$REPORTS_DIR"/*.log; do
        if [[ -f "$log_file" ]]; then
            total_files=$((total_files + 1))
            
            # Count links in this file
            local file_links=$(grep -c "^\s*\[" "$log_file" 2>/dev/null || echo "0")
            total_links=$((total_links + file_links))
            
            # Check if this file has broken links
            if grep -q "ERROR:" "$log_file"; then
                files_with_broken_links=$((files_with_broken_links + 1))
                local file_broken=$(grep -c "^\s*\[✖\]" "$log_file" 2>/dev/null || echo "0")
                broken_links=$((broken_links + file_broken))
            fi
        fi
    done
    
    echo "- **Total Files Checked**: $total_files" >> "$report_file"
    echo "- **Files with Broken Links**: $files_with_broken_links" >> "$report_file"
    echo "- **Total Links Checked**: $total_links" >> "$report_file"
    echo "- **Broken Links Found**: $broken_links" >> "$report_file"
    echo "" >> "$report_file"
    
    if [[ $broken_links -eq 0 ]]; then
        echo "🎉 **Status**: All links are working!" >> "$report_file"
    else
        echo "⚠️ **Status**: $broken_links broken links need attention" >> "$report_file"
    fi
    
    echo "" >> "$report_file"
    echo "## Detailed Results" >> "$report_file"
    echo "" >> "$report_file"
    
    # Add detailed results from each log file
    for log_file in "$REPORTS_DIR"/*.log; do
        if [[ -f "$log_file" ]]; then
            local filename=$(basename "$log_file" .log)
            echo "### $filename" >> "$report_file"
            echo "" >> "$report_file"
            echo '```' >> "$report_file"
            cat "$log_file" >> "$report_file"
            echo '```' >> "$report_file"
            echo "" >> "$report_file"
        fi
    done
    
    echo "## Recommendations" >> "$report_file"
    echo "" >> "$report_file"
    
    if [[ $broken_links -gt 0 ]]; then
        echo "### Immediate Actions" >> "$report_file"
        echo "1. Review broken links listed above" >> "$report_file"
        echo "2. Update or remove invalid URLs" >> "$report_file"
        echo "3. Check if external services are temporarily down" >> "$report_file"
        echo "4. Verify internal file paths exist" >> "$report_file"
        echo "" >> "$report_file"
    fi
    
    echo "### Ongoing Monitoring" >> "$report_file"
    echo "- Run this check weekly or before releases" >> "$report_file"
    echo "- Add link checking to CI/CD pipeline" >> "$report_file"
    echo "- Consider using link checking GitHub Actions" >> "$report_file"
    echo "- Monitor external dependencies for changes" >> "$report_file"
    echo "" >> "$report_file"
    
    echo "---" >> "$report_file"
    echo "*Report generated by Documentation Link Monitor*" >> "$report_file"
    
    echo -e "${GREEN}📊 Link health report generated: $report_file${NC}"
}

# Main execution
cd "$FRONTEND_DIR"

echo -e "${YELLOW}🧹 Cleaning previous reports...${NC}"
rm -f "$REPORTS_DIR"/*.log

failed_files=0

echo -e "${YELLOW}🔍 Checking documentation links...${NC}"

# Check main README
if ! check_file_links "$REPO_ROOT/README.md"; then
    failed_files=$((failed_files + 1))
fi

# Check all markdown files in docs directory
find "$DOCS_DIR" -name "*.md" -type f | while read -r file; do
    if ! check_file_links "$file"; then
        failed_files=$((failed_files + 1))
    fi
done

# Check markdown files in frontend
find "$FRONTEND_DIR" -name "*.md" -not -path "*/node_modules/*" -not -path "*/dist/*" -not -path "*/build/*" -type f | while read -r file; do
    if ! check_file_links "$file"; then
        failed_files=$((failed_files + 1))
    fi
done

echo ""
echo -e "${YELLOW}📊 Generating comprehensive report...${NC}"
generate_link_report

echo ""
if [[ $failed_files -eq 0 ]]; then
    echo -e "${GREEN}🎉 All documentation links are healthy!${NC}"
    exit 0
else
    echo -e "${RED}⚠️  Found issues in $failed_files files. Check the detailed report for specifics.${NC}"
    echo -e "${BLUE}💡 Run 'npm run docs:fix' to attempt automatic fixes.${NC}"
    exit 1
fi
